name: Test pipeline

on:
  push:
    branches:
      - main
env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: set up environment
        run: |
          export MONGODB_URL=${{ secrets.MONGO_DB_URL }}
          export GOOGLE_BOOKS_API_KEY=${{ secrets.GOOGLE_BOOKS_API_KEY }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest
      - name: Run Flake8
        run: |
        #          flake8 --max-line-length 198
      - name: Run pytest
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: set up environment
        run: |
          export MONGODB_URL=$MONGODB_URL
          export GOOGLE_BOOKS_API_KEY=$GOOGLE_BOOKS_API_KEY
      - name: Setup Python
        uses: actions/setup-python@v2

        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest
      - name: Run Flake8
        run: |
        #          flake8 --max-line-length 198
      - name: Run pytest
        run: pytest
      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd /home/ubuntu/online_books_search
            git pull
            dvc pull -f
            pip install -r requirements.txt
            uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
      

      
        
        
